### ISSUE TITLE
Animated gifs broken with certain images

### ISSUE THREAD

**Issue by Soleone** [trevor/ImageMagick#2]
## Problem

When resizing certain animated gifs the resulting image appears "broken":
![broken image](https://cdn.shopify.com/s/files/1/0000/0968/products/radient_small.gif)
## Replication Steps

Download the original animated gif

![original-image](https://cdn.shopify.com/s/files/1/0000/0968/products/radient.gif)

Convert using `convert -resize 100x75 radient.gif radient1_small.gif`
## More information

It looks like the offset is not properly set on the resized version.

Frames of the original image:

![original-frames](https://img.skitch.com/20121001-xrt2d2ujqmwj6cuajdd98h47sb.jpg)

Frames of the resized image:

![resized-frames](https://img.skitch.com/20121001-pda5msye3taq2gb3akfbe246ne.jpg)

**Comment by wisq** [comment]
I was the one that mentioned the whole "offset" thing (with screenshots from the Gimp's layers viewer), but now I realise, the frames beyond the first aren't being offset, they're just being resized incorrectly.  Even if they were moved to the correct position, they would be too large.

I guess it's misreading the sizes of the additional frames, or something.  Not sure.

**Comment by trevor** [comment]
this is a git mirror since imagemagick is still using subversion. i'm not a maintainer.

**Comment by Soleone** [comment]
okay, sent this report to magick-bugs@imagemagick.org
