### ISSUE TITLE
It would be great to create a Podscpec, to allow this library to be used via CocoaPods

### ISSUE THREAD

**Issue by jasperblues** [trevor/ImageMagick#3]

**Comment by trevor** [comment]
hi @jasperblues, this is just a mirror since ImageMagick devs are still using svn.

you may want to look at their forum here: http://www.imagemagick.org/discourse-server/viewforum.php?f=3

**Comment by jasperblues** [comment]
Hi Trevor, 

I did find some pre-compiled binaries of ImageMagick for iOS, published by Claudio . . it would be an easy step to have these available for installation via CocoaPods - just a matter of packaging the binaries and headers. . It would be nice to support OSX installation this way too. . . .. 

. . . I'll follow it up.
